spring:
  application:
    name: msnotification
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  web:
    locale-resolver: fixed
    locale: pt_BR
  mvc:
    format:
      date-time: iso
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db_notifications
      authentication-database: admin
      username: root
      password: root
server:
  port: 8082
mq:
  queues:
    ms-notification: ms-notification